# Generated by Django 4.0.4 on 2022-06-16 06:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='project',
            name='start_time',
        ),
        migrations.AddField(
            model_name='project',
            name='end_date',
            field=models.DateField(default=datetime.date(2022, 6, 16)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.DateField(default=datetime.date(2022, 6, 16)),
            preserve_default=False,
        ),
    ]
