# Generated by Django 4.0.4 on 2022-06-16 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_remove_project_end_time_remove_project_start_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='technologies',
            new_name='tools_used',
        ),
    ]
