# Generated by Django 4.0.4 on 2022-06-16 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_rename_technologies_project_tools_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='technology',
            name='type',
            field=models.CharField(choices=[('1', 'Programming language'), ('2', 'Library/framework')], default='1', max_length=50),
            preserve_default=False,
        ),
    ]
