# Generated by Django 4.0.4 on 2022-06-16 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_technology_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technology',
            name='type',
            field=models.CharField(choices=[('Programming language', 'Programming language'), ('Library/framework', 'Library/framework')], max_length=50),
        ),
    ]
