# Generated by Django 4.0.4 on 2022-06-16 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_technology_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='make_public',
            field=models.BooleanField(default=True),
        ),
    ]
