# Generated by Django 4.0.4 on 2022-06-16 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_project_make_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technology',
            name='type',
            field=models.CharField(choices=[('Programming language', 'Programming language'), ('Library/framework', 'Library/framework'), ('Database', 'Database')], max_length=50),
        ),
    ]
