# Generated by Django 4.0.4 on 2022-06-16 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_technology_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technology',
            name='type',
            field=models.CharField(choices=[('Programming language', 'Programming language'), ('Library/framework', 'Library/framework'), ('Database', 'Database'), ('Cloud computing service', 'Cloud computing service')], max_length=50),
        ),
    ]
