# Generated by Django 4.0.4 on 2022-06-16 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_projectimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectimage',
            name='upload_date',
        ),
        migrations.AddField(
            model_name='projectimage',
            name='upload_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
