# Generated by Django 4.0.4 on 2022-06-17 01:00

from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_alter_projectimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(upload_to=projects.models.ProjectImage.get_upload_path),
        ),
    ]
