# Generated by Django 4.0.4 on 2022-06-17 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_rename_image_projectimage_image_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='page_description',
            field=models.TextField(default='TODO'),
            preserve_default=False,
        ),
    ]
