# Generated by Django 4.0.4 on 2022-06-17 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_projectimage_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectimage',
            old_name='image_path',
            new_name='save_path',
        ),
    ]
