# Generated by Django 4.0.4 on 2022-06-17 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_rename_image_path_projectimage_save_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectimage',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
