# Generated by Django 4.0.4 on 2022-06-19 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_alter_project_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectimage',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
