# Generated by Django 4.0.4 on 2022-06-20 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0025_projectimage_display_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technology',
            name='type',
            field=models.CharField(choices=[('Programming language', 'Programming language'), ('Library/framework', 'Library/framework'), ('Database', 'Database'), ('Cloud computing service', 'Cloud computing service'), ('Other', 'Other')], max_length=50),
        ),
    ]
