# Generated by Django 4.0.4 on 2022-06-23 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0026_alter_technology_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectimage',
            old_name='save_path',
            new_name='image',
        ),
    ]
