# Generated by Django 4.0.4 on 2022-06-25 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0028_alter_projectimage_display_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectimage',
            name='show',
            field=models.BooleanField(default=True),
        ),
    ]
