# Generated by Django 4.0.4 on 2022-06-25 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0029_projectimage_show'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectimage',
            name='display_order',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='Lower values will be shown before higher values.'),
        ),
    ]
