# Generated by Django 4.0.4 on 2022-06-25 20:56

from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0030_alter_projectimage_display_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectimage',
            name='display_order',
            field=models.PositiveIntegerField(default=0, help_text='Lower values will be shown before higher values.'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(editable=False, upload_to=projects.models.ProjectImage.get_upload_path),
        ),
    ]
