# Generated by Django 4.0.4 on 2022-06-25 20:57

from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0031_alter_projectimage_display_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(upload_to=projects.models.ProjectImage.get_upload_path),
        ),
    ]
