# Generated by Django 4.0.4 on 2022-07-08 18:04

from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0032_alter_projectimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='background_image',
            field=models.ImageField(blank=True, upload_to=projects.models.Project.get_upload_path),
        ),
    ]
