# Generated by Django 4.0.4 on 2022-06-17 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='email',
            field=models.EmailField(default='example@gmail.com', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='time_submitted',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.CharField(max_length=3000),
        ),
    ]
