# Generated by Django 4.0.4 on 2022-06-17 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_message_email_message_time_submitted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.TextField(max_length=3000),
        ),
    ]
